sudo: false
language: python
dist: focal
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11-dev"
  - "pypy3"
  - "nightly"
install:
  - pip install -U importlib-metadata
  - pip install -U pip setuptools
  - pip install tox-travis coveralls
script: tox
after_success: coveralls
branches:
  only:
    - develop
    - master
    - "/^\\d+.\\d+.\\d+$/"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: R4jd1weR3i0SvyW0Rj+XtPz+w68hEr8JoSNXCZgLsp9Akpae9dv2hbJrqX5cQ+PTDDTErjzfVzYqe+SZHOod7/PT8evBFjj0slOEOSh4DJpLBRxjsJ5QWSzWOx8zKIKbcg8KYUZSiq4+ZuWgLFU5iuWysF40qasiy5MVIwh1QP28nf8r0gtrsWW9g2JQvjHz0H5FVzTI/FHp7VEv5p8W48yVTvyV5HLsX66H8x3KAzyG8t5xWcqbRXUSFej2rEZRutEhHKBAqKiwY3XS+B+G0NaC7FRzSSjBoeam1tqVv6TJbD+wmJQTzo36nwr6T22DwODq75lXh87GSBHeyWIYa4EdJ1SOUgs0NDN6C+3/dqBJfvWGcK+0enzgVvSy48yWDAC1f6N1sM7PRgtTZMhGYd/Qm/cC2xVCmTXk04vVsH1aZGiGysI9yKYjfm7nO91ixfe1y4hPztiFrIaFQ0xS+s/7o3y5vdwDa26HqYwcA6D27l1Ql3Kqx/qphr/8BxP9W08N7J0RBZaCbfVjpRlBAL8qIPczVD3C8O+pTwESukZ0PfQMBKsrbS8A/FggbUX74dLpl00F5UTnbjVTRhSl11G+FSE1QhXUN6N7tVH254BHlCas02q0wuEQHjp3a8BXLg2q+Pab2KFPY+uIjO3t93BleVjkmIceP+jAGIz5b/8=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.9
